name: Generar M3U8

on:
  workflow_dispatch: # Ejecutar manualmente desde la pestaña Actions

permissions:
  contents: write

jobs:
  build-hls:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Instalar FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Concatenar videos desde la raíz y generar HLS
        run: |
          # Crea el archivo lista.txt detectando cada .mp4 en la raíz del repositorio
          for f in *.mp4; do echo "file '$PWD/$f'" >> lista.txt; done

          # Unifica los videos y genera playlist.m3u8 con sus fragmentos .ts
          ffmpeg -f concat -safe 0 -i lista.txt -c:v copy -c:a aac -hls_time 6 -hls_list_size 0 -f hls playlist.m3u8

      - name: Guardar y subir archivos al repositorio
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u8 *.ts
          git commit -m "Actualizar lista M3U8" || exit 0
          git push
